services:
  web:
    image: ruby:3.0
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - DATABASE_URL=${DATABASE_URL:-postgres://user:password@db:5432/myapp_development}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
    depends_on:
      - db
      - redis
    profiles:
      - web
      - development
      - test

  frontend:
    image: node:14
    command: npm start
    volumes:
      - ./frontend:/app
    working_dir: /app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
    profiles:
      - frontend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=myapp_development
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  postgres_data:
